# Thank you for introducing the mod.
# You can bridge Discord and Minecraft chat!

# Click here for various links↓.
# GitHub -> https://github.com/KT-Ruxy/Fabricord
# Modrinth -> https://modrinth.com/mod/fabricord


# BotToken for use with Discord.
# To get a BotToken -> https://discord.com/developers/applications
BotToken: ""


# Channel for sending Minecraft logs.
# If Blank, the mod will not send Minecraft Server General Chat to Discord.
# To get a Channel ID -> https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID
Log_Channel_ID: ""


# >----- Advanced Settings -----< #


# The bot's activity can be changed.
# "PLAYING", "STREAMING", "LISTENING" and "WATCHING" are available.
# If blank, "PLAYING" is automatically selected.
Bot_Activity_Status: ""


# The bot's activity text can be changed.
# If blank, "Minecraft" is automatically selected.
Bot_Activity_Message: ""

# The bot's online status can be changed.
# "ONLINE", "IDLE" and "DO_NOT_DISTURB" are available.
# If blank, "ONLINE" is automatically selected.
Bot_Online_Status: ""

# The Log Style can be changed.
# "classic", "modern" are available.
# If blank, "classic" is automatically selected.
Message_Style: ""


# If Message_Style is "modern", you need to set the Webhook URL.
# To get a Webhook URL -> https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
Webhook_URL: ""


# >-----------------------------< #